Cambridge test generation toolflow

* Overview of Cambridge work
** High-level
The goal is to validate a cycle-accurate L3 model of the ARM Cortex-M0 against real
hardware using testing. The tests themselves are randomly-generated code fragments (a
few instructions long), which are executed in both the L3 model (translated to HOL4)
and the hardware, and the results are then compared. The hardware is taken as ground
truth, and the HOL4 model is the object under test.

The basic research problem is that given a random sequence of instructions, it could
be the case that executing those instructions would lead to exceptional behavior
either in the L3 model or in the hardware. Therefore, the authors propose a method to
automatically derive a machine pre-state (in the form of a partial assignment) that
guarantees that a given instruction sequence will be safe. An example is a partial
assignment that guarantees that a particular value contains a valid memory address,
so that a subsequent load or store at the address contained in that register will not
trigger a memory access violation.

The authors translate an L3 cycle-accurate ARM Cortex-M0 model into HOL4, generate
short, random programs for testing, and use the HOL4 logic to express constraints
associated with each instruction instance. These constraints are then fed to an SMT
solver (yices), along with the entire model, which uses all this information to
derive pre-states so that upon execution of the randomly-generated test instructions,
we know that addresses are valid, or that the address is correctly aligned, or any
number of other things.

I do not think this completely solves the problem of how to get the machine into the
calculated pre-state, unless part of the pre-state is that the program counter is
pointing to a sequence of instructions that gets you there. But from what I could
clean, that is not the case.
** Technologies used (software)
*** L3
L3 is an ISA specification language & framework. It is used as the primary source for
the ARM Cortex-M0 software model, but is translated into HOL4, and the HOL4 model is
really the model under scrutiny.
*** HOL4
HOL4 is used a target specification logic for the ARM model (translated from L3). The
semantics of each instruction are modeled as functions transforming a machine
state. The overall step function is modeled as a conditional state transformation --
given a particular instruction instance (with concrete values for all the operands),
an associated HOL4 theorem is produced (using the step function for the instruction)
that expresses the associated state transformation for that instance. See Figure 5
in [1] for an example; basically, the precondition/hypothesis of the theorem
expresses that the PC is properly aligned and points to that instruction instance,
and certain exceptional conditions are false. Assuming said precondition holds, it is
asserted that `NextStateM0 s` is equal to a transformed version of the initial state
`s`. These preconditions are eventually used as constraints for the SMT solver to
ensure valid execution, along with some other constraints that are not specific to
the ISA, but the particular core that the model is being validated against.

Since multiple instructions are generated for testing, HOL4 needs to compose the
symbolic state of each successive instruction and accumulate the associated
constraints.
*** Yices
HolSmtLib is used to convert the generated theorems, constraints and instruction
definitions into SMTLib for use in the Yices SMT solver.
* Incorporation into SSITH tools

