resolver: lts-12.12

packages:
- .
- submodules/bv-sized
- submodules/bv-sized-float
- submodules/elf-edit
- submodules/parameterized-utils
- submodules/softfloat-hs

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
# - base-4.11.1.0
# - bytestring-0.10.8.2
# - containers-0.5.11.0
# - lens-4.17
# - mtl-2.2.2
# - process-1.6.4.0
# - QuickCheck-2.11.3
# - template-haskell-2.13.0.0