/* File: "aes128KeySchedule.c". Automatically generated by SBV. Do not edit! */

#include "aes128Lib.h"

void aes128KeySchedule(const SWord32 *key, SWord32 *encKS)
{
  const SWord32 s0 = key[0];
  const SWord32 s1 = key[1];
  const SWord32 s2 = key[2];
  const SWord32 s3 = key[3];
  static const SWord8 table0[] = {
       99, 124, 119, 123, 242, 107, 111, 197,  48,   1, 103,  43, 254,
      215, 171, 118, 202, 130, 201, 125, 250,  89,  71, 240, 173, 212,
      162, 175, 156, 164, 114, 192, 183, 253, 147,  38,  54,  63, 247,
      204,  52, 165, 229, 241, 113, 216,  49,  21,   4, 199,  35, 195,
       24, 150,   5, 154,   7,  18, 128, 226, 235,  39, 178, 117,   9,
      131,  44,  26,  27, 110,  90, 160,  82,  59, 214, 179,  41, 227,
       47, 132,  83, 209,   0, 237,  32, 252, 177,  91, 106, 203, 190,
       57,  74,  76,  88, 207, 208, 239, 170, 251,  67,  77,  51, 133,
       69, 249,   2, 127,  80,  60, 159, 168,  81, 163,  64, 143, 146,
      157,  56, 245, 188, 182, 218,  33,  16, 255, 243, 210, 205,  12,
       19, 236,  95, 151,  68,  23, 196, 167, 126,  61, 100,  93,  25,
      115,  96, 129,  79, 220,  34,  42, 144, 136,  70, 238, 184,  20,
      222,  94,  11, 219, 224,  50,  58,  10,  73,   6,  36,  92, 194,
      211, 172,  98, 145, 149, 228, 121, 231, 200,  55, 109, 141, 213,
       78, 169, 108,  86, 244, 234, 101, 122, 174,   8, 186, 120,  37,
       46,  28, 166, 180, 198, 232, 221, 116,  31,  75, 189, 139, 138,
      112,  62, 181, 102,  72,   3, 246,  14,  97,  53,  87, 185, 134,
      193,  29, 158, 225, 248, 152,  17, 105, 217, 142, 148, 155,  30,
      135, 233, 206,  85,  40, 223, 140, 161, 137,  13, 191, 230,  66,
      104,  65, 153,  45,  15, 176,  84, 187,  22
  };
  const SWord32 s260 = (s3 << 8) | (s3 >> 24);
  const SWord16 s261 = (SWord16) (s260 >> 16);
  const SWord8  s262 = (SWord8) (s261 >> 8);
  const SWord8  s263 = table0[s262];
  const SWord8  s264 = 1 ^ s263;
  const SWord8  s265 = (SWord8) s261;
  const SWord8  s266 = table0[s265];
  const SWord16 s267 = (((SWord16) s264) << 8) | ((SWord16) s266);
  const SWord16 s268 = (SWord16) s260;
  const SWord8  s269 = (SWord8) (s268 >> 8);
  const SWord8  s270 = table0[s269];
  const SWord8  s271 = (SWord8) s268;
  const SWord8  s272 = table0[s271];
  const SWord16 s273 = (((SWord16) s270) << 8) | ((SWord16) s272);
  const SWord32 s274 = (((SWord32) s267) << 16) | ((SWord32) s273);
  const SWord32 s275 = s0 ^ s274;
  const SWord32 s276 = s1 ^ s275;
  const SWord32 s277 = s2 ^ s276;
  const SWord32 s278 = s3 ^ s277;
  const SWord32 s279 = (s278 << 8) | (s278 >> 24);
  const SWord16 s280 = (SWord16) (s279 >> 16);
  const SWord8  s281 = (SWord8) (s280 >> 8);
  const SWord8  s282 = table0[s281];
  const SWord8  s283 = 2 ^ s282;
  const SWord8  s284 = (SWord8) s280;
  const SWord8  s285 = table0[s284];
  const SWord16 s286 = (((SWord16) s283) << 8) | ((SWord16) s285);
  const SWord16 s287 = (SWord16) s279;
  const SWord8  s288 = (SWord8) (s287 >> 8);
  const SWord8  s289 = table0[s288];
  const SWord8  s290 = (SWord8) s287;
  const SWord8  s291 = table0[s290];
  const SWord16 s292 = (((SWord16) s289) << 8) | ((SWord16) s291);
  const SWord32 s293 = (((SWord32) s286) << 16) | ((SWord32) s292);
  const SWord32 s294 = s275 ^ s293;
  const SWord32 s295 = s276 ^ s294;
  const SWord32 s296 = s277 ^ s295;
  const SWord32 s297 = s278 ^ s296;
  const SWord32 s298 = (s297 << 8) | (s297 >> 24);
  const SWord16 s299 = (SWord16) (s298 >> 16);
  const SWord8  s300 = (SWord8) (s299 >> 8);
  const SWord8  s301 = table0[s300];
  const SWord8  s302 = 4 ^ s301;
  const SWord8  s303 = (SWord8) s299;
  const SWord8  s304 = table0[s303];
  const SWord16 s305 = (((SWord16) s302) << 8) | ((SWord16) s304);
  const SWord16 s306 = (SWord16) s298;
  const SWord8  s307 = (SWord8) (s306 >> 8);
  const SWord8  s308 = table0[s307];
  const SWord8  s309 = (SWord8) s306;
  const SWord8  s310 = table0[s309];
  const SWord16 s311 = (((SWord16) s308) << 8) | ((SWord16) s310);
  const SWord32 s312 = (((SWord32) s305) << 16) | ((SWord32) s311);
  const SWord32 s313 = s294 ^ s312;
  const SWord32 s314 = s295 ^ s313;
  const SWord32 s315 = s296 ^ s314;
  const SWord32 s316 = s297 ^ s315;
  const SWord32 s317 = (s316 << 8) | (s316 >> 24);
  const SWord16 s318 = (SWord16) (s317 >> 16);
  const SWord8  s319 = (SWord8) (s318 >> 8);
  const SWord8  s320 = table0[s319];
  const SWord8  s321 = 8 ^ s320;
  const SWord8  s322 = (SWord8) s318;
  const SWord8  s323 = table0[s322];
  const SWord16 s324 = (((SWord16) s321) << 8) | ((SWord16) s323);
  const SWord16 s325 = (SWord16) s317;
  const SWord8  s326 = (SWord8) (s325 >> 8);
  const SWord8  s327 = table0[s326];
  const SWord8  s328 = (SWord8) s325;
  const SWord8  s329 = table0[s328];
  const SWord16 s330 = (((SWord16) s327) << 8) | ((SWord16) s329);
  const SWord32 s331 = (((SWord32) s324) << 16) | ((SWord32) s330);
  const SWord32 s332 = s313 ^ s331;
  const SWord32 s333 = s314 ^ s332;
  const SWord32 s334 = s315 ^ s333;
  const SWord32 s335 = s316 ^ s334;
  const SWord32 s336 = (s335 << 8) | (s335 >> 24);
  const SWord16 s337 = (SWord16) (s336 >> 16);
  const SWord8  s338 = (SWord8) (s337 >> 8);
  const SWord8  s339 = table0[s338];
  const SWord8  s340 = 16 ^ s339;
  const SWord8  s341 = (SWord8) s337;
  const SWord8  s342 = table0[s341];
  const SWord16 s343 = (((SWord16) s340) << 8) | ((SWord16) s342);
  const SWord16 s344 = (SWord16) s336;
  const SWord8  s345 = (SWord8) (s344 >> 8);
  const SWord8  s346 = table0[s345];
  const SWord8  s347 = (SWord8) s344;
  const SWord8  s348 = table0[s347];
  const SWord16 s349 = (((SWord16) s346) << 8) | ((SWord16) s348);
  const SWord32 s350 = (((SWord32) s343) << 16) | ((SWord32) s349);
  const SWord32 s351 = s332 ^ s350;
  const SWord32 s352 = s333 ^ s351;
  const SWord32 s353 = s334 ^ s352;
  const SWord32 s354 = s335 ^ s353;
  const SWord32 s355 = (s354 << 8) | (s354 >> 24);
  const SWord16 s356 = (SWord16) (s355 >> 16);
  const SWord8  s357 = (SWord8) (s356 >> 8);
  const SWord8  s358 = table0[s357];
  const SWord8  s359 = 32 ^ s358;
  const SWord8  s360 = (SWord8) s356;
  const SWord8  s361 = table0[s360];
  const SWord16 s362 = (((SWord16) s359) << 8) | ((SWord16) s361);
  const SWord16 s363 = (SWord16) s355;
  const SWord8  s364 = (SWord8) (s363 >> 8);
  const SWord8  s365 = table0[s364];
  const SWord8  s366 = (SWord8) s363;
  const SWord8  s367 = table0[s366];
  const SWord16 s368 = (((SWord16) s365) << 8) | ((SWord16) s367);
  const SWord32 s369 = (((SWord32) s362) << 16) | ((SWord32) s368);
  const SWord32 s370 = s351 ^ s369;
  const SWord32 s371 = s352 ^ s370;
  const SWord32 s372 = s353 ^ s371;
  const SWord32 s373 = s354 ^ s372;
  const SWord32 s374 = (s373 << 8) | (s373 >> 24);
  const SWord16 s375 = (SWord16) (s374 >> 16);
  const SWord8  s376 = (SWord8) (s375 >> 8);
  const SWord8  s377 = table0[s376];
  const SWord8  s378 = 64 ^ s377;
  const SWord8  s379 = (SWord8) s375;
  const SWord8  s380 = table0[s379];
  const SWord16 s381 = (((SWord16) s378) << 8) | ((SWord16) s380);
  const SWord16 s382 = (SWord16) s374;
  const SWord8  s383 = (SWord8) (s382 >> 8);
  const SWord8  s384 = table0[s383];
  const SWord8  s385 = (SWord8) s382;
  const SWord8  s386 = table0[s385];
  const SWord16 s387 = (((SWord16) s384) << 8) | ((SWord16) s386);
  const SWord32 s388 = (((SWord32) s381) << 16) | ((SWord32) s387);
  const SWord32 s389 = s370 ^ s388;
  const SWord32 s390 = s371 ^ s389;
  const SWord32 s391 = s372 ^ s390;
  const SWord32 s392 = s373 ^ s391;
  const SWord32 s393 = (s392 << 8) | (s392 >> 24);
  const SWord16 s394 = (SWord16) (s393 >> 16);
  const SWord8  s395 = (SWord8) (s394 >> 8);
  const SWord8  s396 = table0[s395];
  const SWord8  s397 = 128 ^ s396;
  const SWord8  s398 = (SWord8) s394;
  const SWord8  s399 = table0[s398];
  const SWord16 s400 = (((SWord16) s397) << 8) | ((SWord16) s399);
  const SWord16 s401 = (SWord16) s393;
  const SWord8  s402 = (SWord8) (s401 >> 8);
  const SWord8  s403 = table0[s402];
  const SWord8  s404 = (SWord8) s401;
  const SWord8  s405 = table0[s404];
  const SWord16 s406 = (((SWord16) s403) << 8) | ((SWord16) s405);
  const SWord32 s407 = (((SWord32) s400) << 16) | ((SWord32) s406);
  const SWord32 s408 = s389 ^ s407;
  const SWord32 s409 = s390 ^ s408;
  const SWord32 s410 = s391 ^ s409;
  const SWord32 s411 = s392 ^ s410;
  const SWord32 s412 = (s411 << 8) | (s411 >> 24);
  const SWord16 s413 = (SWord16) (s412 >> 16);
  const SWord8  s414 = (SWord8) (s413 >> 8);
  const SWord8  s415 = table0[s414];
  const SWord8  s416 = 27 ^ s415;
  const SWord8  s417 = (SWord8) s413;
  const SWord8  s418 = table0[s417];
  const SWord16 s419 = (((SWord16) s416) << 8) | ((SWord16) s418);
  const SWord16 s420 = (SWord16) s412;
  const SWord8  s421 = (SWord8) (s420 >> 8);
  const SWord8  s422 = table0[s421];
  const SWord8  s423 = (SWord8) s420;
  const SWord8  s424 = table0[s423];
  const SWord16 s425 = (((SWord16) s422) << 8) | ((SWord16) s424);
  const SWord32 s426 = (((SWord32) s419) << 16) | ((SWord32) s425);
  const SWord32 s427 = s408 ^ s426;
  const SWord32 s428 = s409 ^ s427;
  const SWord32 s429 = s410 ^ s428;
  const SWord32 s430 = s411 ^ s429;
  const SWord32 s431 = (s430 << 8) | (s430 >> 24);
  const SWord16 s432 = (SWord16) (s431 >> 16);
  const SWord8  s433 = (SWord8) (s432 >> 8);
  const SWord8  s434 = table0[s433];
  const SWord8  s435 = 54 ^ s434;
  const SWord8  s436 = (SWord8) s432;
  const SWord8  s437 = table0[s436];
  const SWord16 s438 = (((SWord16) s435) << 8) | ((SWord16) s437);
  const SWord16 s439 = (SWord16) s431;
  const SWord8  s440 = (SWord8) (s439 >> 8);
  const SWord8  s441 = table0[s440];
  const SWord8  s442 = (SWord8) s439;
  const SWord8  s443 = table0[s442];
  const SWord16 s444 = (((SWord16) s441) << 8) | ((SWord16) s443);
  const SWord32 s445 = (((SWord32) s438) << 16) | ((SWord32) s444);
  const SWord32 s446 = s427 ^ s445;
  const SWord32 s447 = s428 ^ s446;
  const SWord32 s448 = s429 ^ s447;
  const SWord32 s449 = s430 ^ s448;

  encKS[0] = s0;
  encKS[1] = s1;
  encKS[2] = s2;
  encKS[3] = s3;
  encKS[4] = s275;
  encKS[5] = s276;
  encKS[6] = s277;
  encKS[7] = s278;
  encKS[8] = s294;
  encKS[9] = s295;
  encKS[10] = s296;
  encKS[11] = s297;
  encKS[12] = s313;
  encKS[13] = s314;
  encKS[14] = s315;
  encKS[15] = s316;
  encKS[16] = s332;
  encKS[17] = s333;
  encKS[18] = s334;
  encKS[19] = s335;
  encKS[20] = s351;
  encKS[21] = s352;
  encKS[22] = s353;
  encKS[23] = s354;
  encKS[24] = s370;
  encKS[25] = s371;
  encKS[26] = s372;
  encKS[27] = s373;
  encKS[28] = s389;
  encKS[29] = s390;
  encKS[30] = s391;
  encKS[31] = s392;
  encKS[32] = s408;
  encKS[33] = s409;
  encKS[34] = s410;
  encKS[35] = s411;
  encKS[36] = s427;
  encKS[37] = s428;
  encKS[38] = s429;
  encKS[39] = s430;
  encKS[40] = s446;
  encKS[41] = s447;
  encKS[42] = s448;
  encKS[43] = s449;
}
